ClusterLabs/hawk

Vagrantfile

With this Vagrantfile we are able to use libvirt or virtualbox as a provider for the vagrant setup.

Switched to another openSUSE box and added libvirt support

---

chef/cookbooks/hawk/recipes/webui.rb

We have to move that down. If we are not doing it the process is not
aware of the groupmembership for haclient and this process is not
allowed to execute the hawk_* binaries.

Move systemd start to the bottom

---

tools/hawk_invoke.c

This should fix a potential security hole:
[    8s] hawk.x86_64: W: missing-call-to-setgroups-before-setuid /usr/sbin/hawk_invoke
[    8s] This executable is calling setuid and setgid without setgroups or initgroups.
[    8s] There is a high probability this mean it didn't relinquish all groups, and
[    8s] this would be a potential security issue to be fixed. Seek POS36-C on the web
[    8s] for details about the problem.

Tools: Drop extraneous groups when becoming haclient in hawk_invoke

---

hawk/app/assets/javascripts/application.js
hawk/app/assets/javascripts/module/tags.js
hawk/app/controllers/tags_controller.rb
hawk/app/helpers/tag_helper.rb
hawk/app/models/cib.rb
hawk/app/models/record.rb
hawk/app/models/tag.rb
hawk/app/views/resources/types.html.haml
hawk/app/views/shared/_mainnav.html.haml
hawk/app/views/tags/_form.html.haml
hawk/app/views/tags/backup.html.erb
hawk/app/views/tags/edit.html.haml
hawk/app/views/tags/index.html.haml
hawk/app/views/tags/new.html.haml
hawk/config/routes.rb

Support for creating and editing cluster tags.
Tags are superficially similar to groups, but don't imply any constraints between the resources. They are useful for managing otherwise unrelated resources atomically, for example when moving resources between clusters using booth (geo-clusters).

Tags support (fate#318319)

---

README.asciidoc

While setting up my development environment I found some missing pieces for the Hacking section in the README:
- how to install vagrant libvirt plugin
- how to initialize git submodules
- how to restart hawk-development webUI in case it did not come up

Add some steps to the README's Hacking section

---

chef/cookbooks/hawk/templates/default/systemd.service.erb
hawk/app/assets/javascripts/dashboard.js
hawk/app/assets/javascripts/module/monitor.js
hawk/app/assets/javascripts/module/simulator.js
hawk/app/controllers/application_controller.rb
hawk/app/controllers/monitor_controller.rb
hawk/app/helpers/application_helper.rb
hawk/config/environments/development.rb
scripts/hawk.service.bundle_gems.in
scripts/hawk.service.in

Implement /monitor as a live controller.
This also disables autoloading in development mode, unfortunately. Either we turn off the live controller and multithreading in development, or we lose autoloading.
* Modifies the systemd service to run puma as a single process with 16 threads.
* Refresh bootstrap tables on epoch change.
* Use /monitor in dashboard.

Implement /monitor as a live controller (bsc#947748)

---

hawk/app/views/constraints/types.html.haml
hawk/app/views/resources/types.html.haml
hawk/app/views/wizards/index.html.haml

As discussed, it looked broken in Firefox.
Not entirely sure if I found all places where it occurred.

Fix pull-right icon_tags next to icon_texts in Firefox

---

hawk/app/assets/stylesheets/authentication/_basics.scss
hawk/app/assets/stylesheets/authentication/_media.scss

the footer on the login page is rendered differently than the one in the app itself.
and it behaves wrong on small devices while scrolling.
I added some CSS to make it a [sticky footer](http://getbootstrap.com/examples/sticky-footer/).

make the footer on login page sticky

---

hawk/app/assets/javascripts/module/simulator.js
hawk/app/views/layouts/application.html.haml
hawk/app/views/layouts/withrightbar.html.haml
hawk/app/views/shared/_mainnav.html.haml
hawk/app/views/shared/_simulator.html.haml

It's now in a better place than before for sure.
All my more fancy ideas would have broken the mobile views or made them way more complicated.
This is simple but OK I guess.

move simulator panel to the top

---

hawk/app/controllers/agents_controller.rb

If don't do this, the default value of params will lost after converting from xml to json
e.g. RA vsftpd and mysql has many default values, but they cant be shown on the web, it's strange.
Hash.from_xml will cause the default value lost if the value's type is "string" 
related link:
https://stackoverflow.com/questions/14891912/rails-hash-from-xml-not-giving-expected-results

Dev: Replace type="string" to 'type="text" in ra's meta-data

---

hawk/app/models/primitive.rb

Hi:
For now,  Primitive resource will be successfully created when some parameters are still blank.
This will cause errors at pacemaker(see crm_mon).
We can't prevent user input an invalid parameter, but we can prevent them leaving a blank one.
This is my first try on Hawk/rails:) 
Regards,
xin

Dev: Check whether param's value is blank

---

hawk/app/controllers/locations_controller.rb
hawk/app/controllers/orders_controller.rb
hawk/app/lib/util.rb
hawk/app/models/colocation.rb
hawk/app/models/constraint.rb
hawk/app/models/resource.rb

When adding resources or constraints, we use "crm configure" to verify commits;
Before that, we have already done some checks, such as id's presence and resources.length for colocation, it's better to make sure that these checks have passed successfully, and then, let "crm configure" to verify
For example, when adding a primitive resource,
I forgot to input Resource ID, after submit,
errors list are "ID ID is required, ID Invalid, 2: ocf:Heartbeat:IPaddr2 invalid object id" ,
they are complaining the same thing:)
That's not necessary.

Dev: Make sure no errors before crm configure verify

---

hawk/app/controllers/agents_controller.rb
hawk/app/lib/util.rb
hawk/app/models/primitive.rb

In resource_agents, some boolean param's default value is chaotic,
there are "yes|No|no|1|0" available, 
these default value can not be shown on the attrlist, because thay are not "true|false".
I replaced above options to "true" or "false", and with #110, moved codes to util.rb
Regards,
xin

Dev: Move get_meta_data function to util and do some replaces

---

hawk/app/assets/javascripts/module/attrlist.js
hawk/app/assets/javascripts/module/oplist.js

When adding drbd primitive resource, two monitor options are needed,
one is for Master, the other one is for Slave,
so by default, it's better to show two monitors to avoid user forget to add the second monitor.
When adding mysql or redis, there are three monitors available,
one is for primitive purpose, the other two are for m/s purpose,
because the probability these two RAs as just a primitive resource is much larger than as a m/s resource,
in this situation, I just pick out the monitor for primitive purpose(without role).
Regards,
xin

Dev: Change monitor in oplist for Master/Slave resource

---

hawk/app/models/crm_config.rb
hawk/app/models/template.rb

http://clusterlabs.org/doc/en-US/Pacemaker/1.1-pcs/html/Pacemaker_Explained/s-resource-options.html#_resource_meta_attributes
and in doc, INFINITY is the default value, 
in crmsh, set migration-threshold=3 by default,
I think both 0|3 are OK

Dev: 0 instead of INFINITY means disabled for migration-threshold

---

hawk/app/assets/stylesheets/shared/_form.scss

When adding Score in location, dropdown will create scrollbar on right.
According to https://stackoverflow.com/questions/18918010/bootstrap-dropdown-creates-scrollbar-to-parent-div
use inherit instead of auto can resolve this problem
hope this no any side effect:)
Regards,
xin

Dev: Use "overflow: inherit" to avoid dropdown creates scrollbar

---

hawk/app/assets/javascripts/module/wizards.js

In wizard, when Apply successfully, we no need this btn enabled and clickable,
click "Apply" twice after successfully apply will cause error because use the same id,
this can make user confused
Regards,
xin

Dev: disabled click when wizard apply successfully

---

hawk/app/assets/javascripts/module/wizards.js

In wizards, some steps can be set as enable/disable.
It's better to make related options with same attribution.
Regards,
xin

Dev: Check data-wizard-enable to disable/enable related options

---

hawk/app/assets/javascripts/module/alerts.js
hawk/app/assets/javascripts/module/clones.js
hawk/app/assets/javascripts/module/colocations.js
hawk/app/assets/javascripts/module/constraints.js
hawk/app/assets/javascripts/module/groups.js
hawk/app/assets/javascripts/module/locations.js
hawk/app/assets/javascripts/module/masters.js
hawk/app/assets/javascripts/module/orders.js
hawk/app/assets/javascripts/module/primitives.js
hawk/app/assets/javascripts/module/reports.js
hawk/app/assets/javascripts/module/resources.js
hawk/app/assets/javascripts/module/roles.js
hawk/app/assets/javascripts/module/tags.js
hawk/app/assets/javascripts/module/users.js
hawk/config/routes.rb

Related to https://github.com/ClusterLabs/hawk/issues/151
Dot's are now allowed in the id part of the route and characters which are known to be unsafe or reserved in URIs are excluded.

Medium: Comply routes' id with resources' ID (bsc#1092108)

---

hawk/app/lib/cibtools.rb

in some case, param in determine_online_status_fencing is nil,
this will cause NoMethodError

Api: return nil if elem is nil(fate#323437)

---

hawk/app/models/api/v1/cluster.rb

Why we had hard code here? The property of cluster may be changed
e.g. append a property like "maintenance_mode=false", this cluster property will not be shown
Or, do these hard code property planned to be a "base" info of cluster? 
And other properties as "advance" info?
I think that we should show all of them in api, then classify/sort them in client code

Api: change to_hash function more dynamic(fate#323437)

---

hawk/app/models/api/v1/resource.rb

The value of instance[:state] include ":started" and ":stopped", instead of ":running"

Api: get right status when resource is started(fate#323437)

---

hawk/app/lib/cibtools.rb

This  will cause NoMethodError when resource is failed

Api: instance variable should not use here(fate#323437)

---

hawk/app/models/api/v1/resource.rb

The group/clone/ms resource includes one or more primitive resources;
Even belong to a group/clone/ms, a primitive resource's type should be primitive.
BTW, I think it will be convenient to provide group/clone/ms perspective to look at which primitive resources included, through new rails route or related parameters after "/api/v1/resources"

Api: primitive resource's type should always be primitive(fate#323437)

---

hawk/app/controllers/api/v1/api_controller.rb

In order to fetch data from the api with the client, in addition to the preflight check for the options call, we need to send the allowed headers again with the corresponding request.

Api: Add necessary headers for cross-origin resource sharing

---

hawk/app/models/crm_config.rb
tools/hawk_invoke.c

These should be the only changes needed to make hawk able to handle the new daemon names, and I don't think any critical functionality is affected by not having the changes.

Handle new daemon names in hawk

---

hawk/app/controllers/graphs_controller.rb

A commit [0] in ruby 2.5 removed the Dir::Tmpname#make_tmpname method. This patch works around that removal by implementing a minimalistic version of that method that conforms to the former format of generated filenames.
Fixes bsc#1162221.
[0] https://github.com/ruby/ruby/commit/25d56ea7b7b52dc81af30c92a9a0e2d2dab6ff27

Work around the removal of Dir::Tmpname#make_tmpname (bsc#1162221)

---

hawk/app/models/cib.rb

Hawk2 returns "Low level server error occurred" after authentication if a resource has the same name as a node"
on old right now for waiting other SR

SLE12: Fix bsc#1163381

---

hawk/app/models/cib.rb

Hawk2 returns "Low level server error occurred" after authentication if a resource has the same name as a node"

SLE15: Fix bsc#1163381

---

e2e_test/Dockerfile
e2e_test/hawk_test_driver.py

Adapt hawk_test code to support testing for 12-SP2
Also fix Dockerfile for best & recommended practices (avoid consecutive RUN's that increase image size).

Adapt hawk_test code to support testing for 12-SP2

---

e2e_test/Dockerfile
e2e_test/README.md
e2e_test/hawk_test.py
e2e_test/hawk_test_driver.py

- Rebase Docker image on Leap 15.2 to fix problems with unstable TW build.
- Use TigerVNC instead of Xvfb because Xvfb is inside larger Xorg package
- Remove --test-version option by getting it from /etc/os-release
- Remove useless --prefix option
- Minor fixes

e2e_test: Rebase on Leap 15.2. Remove -p & -t options

---

e2e_test/README.md
e2e_test/hawk_test.py

We must use `VERSION` (which is a string like 12-SPx) instead of `VERSION_ID` which is a float.  We use the former in the code to test versions.

Use VERSION instead of VERSION_ID

---

e2e_test/hawk_test_driver.py

The report generation usually fails over my VPN and times out.
Better drop the timeout and check for the link to the report instead.
Tested with the latest MU's on 12-SP{3,4,5}, 15-GA & 15-SP{1,2}

e2e_test: Drop timeout and look for report instead

---

e2e_test/hawk_test_driver.py

Fixes submitted by @alvarocarvajald
-   Handle false positives in test_remove_virtual_ip
Current code for test_remove_virtual_ip returns True even if it fails to
remove the virtual IP address via hawk, as it is not checking the return
status of self.remove_rsc. This commit fixes this issue.
-  Add error handling for the submit buttons on Virtual IP 
wizard. If the submit buttons cannot be found, current code
still attempts to click on them which causes an Exception. This
in turn abort the entire test. If we catch this error and fail
the test gracefully, the rest of the tests on the UI can continue.

e2e_test: Fixes

---

e2e_test/hawk_test_driver.py

Another fix by @alvarocarvajald
Currently, after test_add_virtual_ip has added a Virtual IP to the cluster, test script will connect to HAWK via the Virtual IP to verify that the address was successfully configured in the cluster. On success, test script will reset the connection address to the one originally supplied in the -H/--host option; however, if connection to HAWK via the Virtual IP is not possible, connection address is not reset and all remaining tests will fail to connect to HAWK.
This commit resets the connection address even on failures, and also rewords the error message to make it more clear.

e2e_test: Reset connection address unconditionally

---

.github/workflows/test-hawk.yaml
scripts/sysconfig.hawk

There is introduced a cd by means of github actions. It creates a basic 2-nodes ha cluster with a `stonith/ssh` resource and runs the `e2e_test` against the cluster. 
Q: Why are the containers started not as 
```
container:
image: ghcr.io/aleksei-burlakov/hawk-node:latest
```
but rather `docker run` ?
A: Because it's the only way to start them with the `--privileged` flag.
Q: Why not use k8s/k3s/helm charts, bash/python/whatsoever scripts to deploy the ha-cluster?
A: Yaml is already good enough.

Add automatic testing for continious developmend

---

hawk/app/controllers/errors_controller.rb
hawk/config/routes.rb

* Extend handling of unmatched paths to all HTTP request types, not only GET.
* When processing an unmatched URL, avoid redirecting to the 404 error page via the HTTP 301 status code but instead directly return the page using code 404.

Improve handling of unmatched paths (bsc#1199258)

---

hawk/app/lib/hawk/secure_cookies.rb

The flag HttpOnly was unconditional. It was set fot all cookies.
This commit gives you a choice. To set the HttpOnly flag you
need to pass the environment variable `HAWK_COOKIE_HTTP_ONLY=true`.
The simplest way to do it is to add it to the /etc/sysconfig/hawk file,
for example
```
$ echo "HAWK_COOKIE_HTTP_ONLY=true" >> /etc/sysconfig/hawk
$ systemctl restart hawk-backend
```

Set HttpOnly by HAWK_COOKIE_HTTP_ONLY=true

---

e2e_test/Dockerfile
e2e_test/hawk_test_driver.py

Minor enhancements to e2e_test:
- Use f-strings
- Drop <12-SP3 test code
- Update geckodriver
- Specify openSUSE registry in Dockerfile
These changes were already tested in all supported SLES versions in openQA / HA Incidents.

Minor enhancements to e2e_test

---

hawk/bin/generate-ssl-cert

It was that if either of the private or public keys were missing both would be recreated. Now, if the private key still exists, only the public key will be recreated.

Don't delete the private key if the public key is missing

---

hawk/app/models/wizard.rb

The category is used as captions and urls,
it should only contain alphanumeric symbols and spaces.

Forbid special symbols in the category

---

hawk/app/models/report.rb

This change should accompish the commits a4969be6 and 6544880e. Basically we make an exception for bzip2 files, in a way that they may come as octet stream.

Fix mime type issue in MS windows

---

hawk/app/controllers/errors_controller.rb

by changing the `protect_from_forgery` action to `:exception`

Enforse CSRF in errors_controller.rb

---

hawk/app/lib/hawk/secure_cookies.rb

The HttpOnly secure flag was set as default in 8db131080e, but then I changed my mind and made it parametrisable in 0008fdf613f7. However, after discussing with Johannes Segitz <jsegitz@suse.com> we decided to revert the 0008fdf613f7 and use the HttpOnly by default.

Enable HttpOnly secure flag by default

---

hawk/app/controllers/application_controller.rb
hawk/app/controllers/sessions_controller.rb
hawk/app/lib/invoker.rb
hawk/app/lib/util.rb
hawk/app/models/cib.rb
hawk/app/views/shared/_flash.html.erb

Basically we partitially revert 793b120cad
and improve the hawk_invoke so that it works as non-root.
Like in 793b120cad we do ` $ su -c <user>`, but instead of running as `root` we do it under `hacluster` (the hawk service is running by default under `hacluster`). And doing `hacluster$ su -c <user>` (under hacluster) requires the password of the `<user>` , so we store it in the `session` variable.

Enable ACL

---

e2e_test/hawk_test_ssh.py

Newer versions of crmsh will report that a stonith resource is in maitenance by the `maintenance` keyword, while older versions use `unmanaged` instead.
This was addressed in commit b3998aaf6b23053772ad09eaa2e33964229c6fdb, but it is also causing the test script to connect twice to the cluster nodes over SSH to check first for `unmanaged` and then for `maintenance`.
Changes provided in this commit extend the function `check_cluster_conf_ssh` so it is able to match any or all of the keywords passed to it.
It does so by introducing a third parameter to `check_cluster_conf_ssh` so the function is able to match all provided keywords, or just one of them. The extra parameter informs the function whether it should do an "or" (set to false, i.e., "and", by default) and return True when any of …

Check rsc stonith is in maintenance by either of 2 keywords

---

e2e_test/hawk_test_driver.py

The issue happened on 12-SP5 after updating the sleep time from the current master branch(commit: 1219b4b8d8766868e1762f7377459f7b196ef74a) in **ClusterLabs**
https://openqa.suse.de/tests/14048367#step/hawk_gui/82
and everything worked well after changing the sleep time back.

Increase the test delays as they were before

---

hawk/app/lib/crm_script.rb
hawk/app/lib/hb_report.rb
hawk/app/lib/invoker.rb
hawk/app/models/cib.rb
hawk/app/models/cluster.rb
hawk/app/models/report.rb
hawk/app/models/wizard.rb

Previously, all programs were executed as hacluster. In the 618cbc8 was enabled ACL, so that each program is executed under the current user. This however requires /usr/sbin to be in the $PATH. So here we prepend all executables with /usr/sbin.

Fix: prepend all executable with /usr/sbin
