ClusterLabs/hawk

chef/cookbooks/hawk/attributes/default.rb, chef/cookbooks/hawk/metadata.rb, chef/cookbooks/hawk/recipes/node.rb, chef/cookbooks/hawk/recipes/webui.rb, scripts/hawk.redhat.in, scripts/hawk.service.in, scripts/hawk.suse.in
* Fix the path of the ssl generate script (It's in the bin folder since rails 4)
* Install hawk from OBS devel project within vagrant
=> Rails 4 fixes

hawk/config/boot.rb
Without that the current rpm install doesn't work without database config and so on.
=> We don't want to load all rails components

hawk/app/models/cib_object.rb, hawk/app/views/clones/_form.html.erb, hawk/app/views/colocations/_form.html.erb, hawk/app/views/explorer/_pe_list.html.erb, hawk/app/views/groups/_form.html.erb, hawk/app/views/locations/_form.html.erb, hawk/app/views/masters/_form.html.erb, hawk/app/views/orders/_form.html.erb, hawk/app/views/primitives/_form.html.erb, hawk/app/views/roles/_form.html.erb, hawk/app/views/tickets/_form.html.erb, hawk/app/views/users/_form.html.erb
A bug introduced with rails 4, errors have to be a hash so i converted
all errors temporary to an hash until the new ui gets in.
=> Fixed error messages within forms

bootstrap-hawk/index.html, bootstrap-hawk/login.html
Our designer might be Italian but the page titles probably shouldn't be :)
=> Fix typo in index and login page title

hawk/app/assets/javascripts/application.js
As all other ways to fix the footer issues have downsides, it's time to bring the big guns.
=> use MutationObserver to fix the footer issue

hawk/app/views/configs/edit.html.haml
Fix the tabs to look the same as the Status view.
=> UI: Fix tabs in edit view

chef/cookbooks/hawk/templates/default/systemd.service.erb, hawk/bin/hawk, hawk/config/environments/development.rb, hawk/config/environments/production.rb, hawk/config/environments/test.rb, hawk/config/puma.rb, rpm/sysconfig.hawk, scripts/hawk.service.bundle_gems.in, scripts/hawk.service.in
**Changes**:
- Dev: Add server command to bin/hawk
- Dev: Handle environment variables in puma.rb
- Dev: Log to STDOUT in development mode
- Dev: Clean up thread/process configuration
=> Dev: Better server configuration and management

Vagrantfile, chef/cookbooks/hawk/attributes/node.rb, chef/cookbooks/hawk/attributes/webui.rb, chef/cookbooks/hawk/recipes/node.rb, chef/cookbooks/hawk/recipes/webui.rb, chef/cookbooks/hawk/templates/default/global_common.conf.erb, chef/cookbooks/hawk/templates/default/r0.res.erb, hawk/app/models/cib.rb, hawk/app/views/resources/events.html.erb
* Check DRBD status if active on local node
* Display a warning for certain disk/connection states
* Configure a shared DRBD device in the Hawk vagrant setup
=> Check DRBD status if active on local node

hawk/app/assets/stylesheets/_theme.scss, hawk/app/assets/stylesheets/authentication/_basics.scss, hawk/app/assets/stylesheets/authentication/_foot.scss, hawk/app/controllers/sessions_controller.rb, hawk/app/models/profile.rb, hawk/app/views/layouts/authentication.html.erb, hawk/config/routes.rb
This pull request replaces #85 and adds the necessary backend bits to make the language selection drop down work on the login screen.
Closes: #85
=> UI: Implement login screen language selection

hawk/app/assets/javascripts/application.js, hawk/app/assets/stylesheets/application/_content.scss, hawk/app/assets/stylesheets/application/_media.scss, hawk/app/views/layouts/withrightbar.html.erb
Reverts ClusterLabs/hawk#92
Sidebar is now broken:
=> Revert "Left menu scroll"

Makefile, README.asciidoc, doc/design-old.txt, hawk/public/500.html, rpm/hawk-rpmlintrc, rpm/hawk.spec
- Change the installation paths from /srv/www/hawk to /usr/share/hawk
for both suse and redhat systems.
- Change the installation paths in the documentation (README.asciidoc)
=> Dev: Change the installation paths to /usr/share/.

hawk/app/assets/javascripts/module/attrlist.js, hawk/app/assets/javascripts/module/primitives.js
For RA's required parameters, it shouldn't be removed,
so I disabled the remove btn when meets required params:)
Hope that make sense:)
regards,
xin
=> Dev: Required param should not be removed

hawk/app/controllers/application_controller.rb, hawk/app/controllers/clones_controller.rb, hawk/app/controllers/colocations_controller.rb, hawk/app/controllers/groups_controller.rb, hawk/app/controllers/locations_controller.rb, hawk/app/controllers/masters_controller.rb, hawk/app/controllers/orders_controller.rb, hawk/app/controllers/primitives_controller.rb, hawk/app/lib/util.rb
Like how to handle error messages in primitives controller,
I let the error messages shown on the location/colocation/order page.
So, I have closed issues #118.
=> Dev: Let error message shown in location/colocation/order page

hawk/app/models/clone.rb, hawk/app/models/group.rb, hawk/app/models/master.rb, hawk/app/models/tableless.rb
hi ayoub,
I have closed #124 and create this commit without conflicts
Regards,
xin
=> Dev: Set target-role default value to Stopped

.gitignore, .travis.yml, hawk/app/models/profile.rb, hawk/spec/models/profile_spec.rb, test/_internal_runner.sh, test/run
I created a docker container to run the test suite in, and tried switching to rspec for tests. Created one test, and found an issue immediately. So maybe it's a good idea ;)
=> Switch to rspec for tests

hawk/app/assets/javascripts/module/resources.js, hawk/app/controllers/resources_controller.rb, hawk/app/models/bundle.rb, hawk/app/models/cib.rb, hawk/app/models/node.rb, hawk/app/models/record.rb, hawk/app/models/resource.rb, hawk/app/views/cib/show.html.erb
This allows the "details" pane to basically work for bundles in the status page.
=> Add minimal bundle model object (fate#324558)

.rubocop.yml, hawk/app/assets/javascripts/module/nodes.js, hawk/app/assets/javascripts/module/statustable.js, hawk/app/controllers/nodes_controller.rb, hawk/app/lib/cibtools.rb, hawk/app/models/cib.rb, hawk/app/models/node.rb, hawk/app/views/dashboards/show.html.erb, hawk/app/views/nodes/show.html.erb
Figuring out the state of guest nodes is non-trivial
based on the information given by the CIB. I think
this is mostly right... :(
=> High: Calculate guest node state correctly (bsc#1074856)

hawk/app/models/colocation.rb, hawk/app/models/constraint.rb, hawk/app/models/order.rb, hawk/app/validators/colocation_validator.rb, hawk/app/validators/order_validator.rb, hawk/spec/models/colocation_spec.rb, hawk/spec/models/order_spec.rb
The validation of the colocation model gets triggered to late (actually after the constraint one's). Since it works on other places like in the order model it still need's some more investigation. This PR is just the first solution that i found and seemed to work. But it needs some more testing and i'm pretty sure there is a smarter way :) I will continue working on it.
=> Dev: Create seperate validation class for colocation and order model

hawk/app/controllers/api/v1/nodes_controller.rb, hawk/app/controllers/api/v1/resources_controller.rb
=> Api: implement show method in controller(fate#323437)

hawk/app/models/api/v1/resource.rb
Just for convenience if client side get the data
=> Api: Add 'belong' in resource return value(fate#323437)

hawk/app/assets/javascripts/module/resources.js
@ayoub-belarbi please wait with the merge until tomorrow, i have one more question regarding this commit :)
=> Medium: Make resource stop/start icon dependent on target-role (bsc#1076421)

hawk/app/controllers/sessions_controller.rb
Just a commit to show that it is in progress, will commit the rest of it tomorrow.
=> Hawk server-side cookie handling

tools/hawk_invoke.c
=> preserve CIB_server et al environment variables (connect to remote)

hawk/Gemfile, hawk/app/controllers/agents_controller.rb, hawk/app/lib/util.rb, hawk/app/models/crm_config.rb, hawk/app/models/primitive.rb, hawk/config/application.rb
- this patch backport the change/patch, and also adapt the approach for different binaries location, since we need to do this for different OS version which might use diff binaries.
- it removes devel gems which aren't needed.
I have already tested this and worked well. I will rebuild the pkg and retest it just in case. (that's why wip) but is already reviewable
=> Fix bsc1165587 and other minor changes

hawk/app/models/cib.rb
Hawk2 returns "Low level server error occurred" after authentication if a resource has the same name as a node"
=> FACTORY: Fix bsc116381 

hawk/app/controllers/application_controller.rb, hawk/app/controllers/reports_controller.rb
Within this pr, users belonging into haclient group can acces to history
explorer page and create reports etc. (#pm-51)
=> Allow also users in haclient to view history explorer

e2e_test/.pylintrc, e2e_test/Dockerfile
Fix minor bug in Dockerfile and add an ignore keyword to .pylintrc
=> Fix Dockerfile & .pylintrc

hawk/Gemfile, hawk/config/boot.rb
Update rubygem puma gem to work with new rubygem puma
=> Update puma to 3.11.4 in ordert to support

hawk/config/puma.rb
this pr will provide small changes for enhancig hawk on sle12:
- rebuild hawk with latest puma rpm ( isn't visible here)
- remove config puma for dev env.
- pass disabling TLS 1.0 and 1.1 via Sysconfig variable ( managed in RPM)
=> Enhance puma on sle12

hawk/app/controllers/application_controller.rb
=> Fix command call

hawk/app/models/report.rb
sanitize filename during upload
=> sanitize filenames

hawk/app/lib/crm_script.rb, hawk/app/models/api/v1/cluster.rb
=> Fix wizards ui

e2e_test/Dockerfile, e2e_test/hawk_test.py, e2e_test/hawk_test_driver.py, e2e_test/hawk_test_results.py, e2e_test/hawk_test_ssh.py
This PR was tested on all supported SLES releases.
Changes:
- Rebase Docker image on Leap 15.3
- Use latest geckodriver
- Update code to use Python 3.6 features like f-strings.
=> Rebase Docker image, use latest geckodriver and use Python 3.6

hawk/app/lib/crm_script.rb, hawk/app/lib/invoker.rb, hawk/app/models/report.rb
Backport of 37bdface5c3bd487662a48dacf1acbeb4feef14a
from master branch
=> Remove unnecessary chmod

hawk/app/models/cib.rb
Partial upgrade detection is based on reading `crm_feature_set` operation attributes but they record only a version of the designated controller which was active when a given operation was run. Fix this detection by instead querying `#feature-set` transient attributes.
=> Fix detection of partial upgrade

hawk/Gemfile, hawk/config/boot.rb
Otherwise there is a gem-conflict
=> Fix the sass-rails version on ~5.0

hawk/app/views/orders/_form.html.erb
Score is the numeric value of the constraint.
Kind is its kind: Mandatory, Optional, Serialize.
=> Dev: rename 'Score' to 'Kind'

e2e_test/hawk_test.py, e2e_test/hawk_test_driver.py, e2e_test/hawk_test_results.py, e2e_test/hawk_test_ssh.py
According to the request in https://jira.suse.com/browse/TEAM-9131, add doc strings for all functions in all python scripts within the repository to summary what the functions do.
=> Add docstring to functions in hawk_test
